name: flutter_dialpad
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dtmf: ^2.0.2
  flutter_masked_text2:
    git:
        url: https://github.com/cybex-dev/flutter_masked_text
        ref: 156f63b77d23148d9f1544230e3201ab6172f470 # branch 'fix_null_mask'
  uikit:
    path: ../uikit
  contacts:
    path: ../contacts

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: