name: audio_player
description: app audio player

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.10+1
  media_kit_libs_audio: ^1.0.4
  rxdart:
  uikit:
    path: ../uikit