include: package:lints/recommended.yaml

analyzer:
  exclude: [ app/build/**, build/**, app/lib/**.g.dart, ./**/**.g.dart, test/**.g.dart, flutter_test/**.g.dart, codegen_config/flutter/**, packages/**.g.dart, packages/**.dart, ]
  #  strong-mode:
  #    implicit-casts: false # Will cause a lot of refactoring
  #    implicit-dynamic: false # Will cause a lot of refactoring
  errors:
    #
    # Error rules
    #
    avoid_empty_else: error
    avoid_print: error
    avoid_relative_lib_imports: error
    avoid_returning_null_for_future: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    avoid_web_libraries_in_flutter: error
    cancel_subscriptions: error
    comment_references: ignore
    control_flow_in_finally: error
    diagnostic_describe_all_properties: ignore # Very annoying. "ignore" for now.
    empty_statements: error
    hash_and_equals: error
    invalid_use_of_protected_member: warning # Will require some refactoring. "Warning" for now.
    invalid_use_of_visible_for_testing_member: warning # Will require some refactoring. "Warning" for now.
    invariant_booleans: info # Wait until there're no false positives in `async/await` case. For now only "info".
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: warning # TODO: make error after initial setup
    missing_required_param: error
    missing_return: error
    missing_enum_constant_in_switch: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    no_logic_in_create_state: error
    prefer_relative_imports: info
    prefer_void_to_null: error
    test_types_in_equals: error
    throw_in_finally: error
    unnecessary_statements: warning
    unrelated_type_equality_checks: error
    use_key_in_widget_constructors: warning # Will require some refactoring. "Warning" for now.
    valid_regexps: error
    #
    # Style rules
    #
    always_declare_return_types: error
    always_put_required_named_parameters_first: info
    always_require_non_null_named_parameters: error
    annotate_overrides: info
    avoid_bool_literals_in_conditional_expressions: error
    avoid_catching_errors: warning
    avoid_classes_with_only_static_members: warning # Will require some refactoring. "Warning" for now.
    avoid_equals_and_hash_code_on_mutable_classes: error
    must_be_immutable: warning # Will require a lot of refactoring. "Warning" for now.
    avoid_escaping_inner_quotes: warning
    avoid_implementing_value_types: info
    avoid_init_to_null: error
    avoid_positional_boolean_parameters: info # Will require a lot of refactoring. "Info" for now.
    avoid_private_typedef_functions: info
    avoid_redundant_argument_values: info
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    avoid_returning_null: warning
    avoid_returning_null_for_void: error
    avoid_setters_without_getters: warning
    avoid_single_cascade_in_expression_statements: error
    avoid_types_on_closure_parameters: info # Wait until type inference gets better. For now only "info".
    avoid_unnecessary_containers: warning # Will require a lot of refactoring. "Warning" for now.
    avoid_unused_constructor_parameters: warning # Will require a lot of refactoring. "Warning" for now.
    avoid_void_async: warning # Will require a lot of refactoring. "Warning" for now.
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    constant_identifier_names: warning # Will require a lot of refactoring. "Warning" for now.
    curly_braces_in_flow_control_structures: warning # Will require a lot of refactoring. "Warning" for now.
    directives_ordering: error
    combinators_ordering: info
    empty_catches: warning # Will require some refactoring. "Warning" for now.
    empty_constructor_bodies: info
    # exhaustive_cases: error # unreleased yet
    file_names: warning # Will require some refactoring. "Warning" for now.
    implementation_imports: error
    join_return_with_assignment: info
    leading_newlines_in_multiline_strings: warning # Will require some refactoring. "Warning" for now.
    library_names: error
    library_prefixes: error
    lines_longer_than_80_chars: info # Will require some refactoring. "Info" for now.
    missing_whitespace_between_adjacent_strings: error
    # no_default_cases: error # unreleased yet
    no_runtimeType_toString: error
    non_constant_identifier_names: warning # Will require some refactoring. "Warning" for now.
    null_closures: error
    omit_local_variable_types: info # Will require a lot refactoring. "Info" for now.
    one_member_abstracts: warning # Will require some refactoring. "Warning" for now.
    only_throw_errors: error
    overridden_fields: warning # Will require some refactoring. "Warning" for now.
    package_prefixed_library_names: error
    parameter_assignments: warning # Will require some refactoring. "Warning" for now.
    prefer_adjacent_string_concatenation: info
    prefer_asserts_in_initializer_lists: error
    prefer_collection_literals: warning # Will require some refactoring. "Warning" for now.
    prefer_conditional_assignment: error
    prefer_const_constructors: info # Will require a lot of refactoring. "Info" for now.
    prefer_const_constructors_in_immutables: info # Will require a lot of refactoring. "Info" for now.
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error
    prefer_constructors_over_static_methods: error
    prefer_contains: error
    prefer_equal_for_default_values: error
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: warning # Will require a lot of refactoring. "Warning" for now.
    prefer_for_elements_to_map_fromIterable: warning
    prefer_function_declarations_over_variables: error
    prefer_generic_function_type_aliases: error
    prefer_if_elements_to_conditional_expressions: warning # Will require some refactoring. "Warning" for now.
    prefer_if_null_operators: warning # Will require some refactoring. "Warning" for now.
    prefer_initializing_formals: warning # Will require some refactoring. "Warning" for now.
    prefer_inlined_adds: error
    prefer_int_literals: info # Will require a lot of refactoring. "Info" for now.
    prefer_interpolation_to_compose_strings: info # Will require a lot of refactoring. "Info" for now.
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_is_not_operator: error
    prefer_iterable_whereType: error
    prefer_null_aware_operators: error
    prefer_single_quotes: info # Will require a lot of refactoring. "Info" for now.
    prefer_spread_collections: error
    prefer_typing_uninitialized_variables: error
    recursive_getters: error
    # sized_box_for_whitespace: error # available in Dart SDK 2.9.0
    slash_for_doc_comments: error
    sort_child_properties_last: warning # Will require some refactoring. "Warning" for now.
    sort_constructors_first: info # Will require some refactoring. "Info" for now.
    sort_unnamed_constructors_first: info # Will require some refactoring. "Info" for now.
    type_annotate_public_apis: warning # Will require a lot of refactoring. "Warning" for now.
    type_init_formals: error
    unawaited_futures: info # Will require a lot of refactoring. "Info" for now.
    unnecessary_await_in_return: warning # Will require some refactoring. "Warning" for now.
    unnecessary_brace_in_string_interps: info
    unnecessary_const: error
    unnecessary_getters_setters: error
    unnecessary_lambdas: warning # Will require some refactoring. "Warning" for now.
    unnecessary_new: warning # Will require some refactoring. "Warning" for now.
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_overrides: error
    unnecessary_parenthesis: error
    unnecessary_raw_strings: error
    unnecessary_string_escapes: error
    unnecessary_string_interpolations: error
    unnecessary_this: warning # Will require some refactoring. "Warning" for now.
    use_full_hex_values_for_flutter_colors: error
    use_function_type_syntax_for_parameters: error
    # use_is_even_rather_than_modulo: error # unreleased yet
    use_raw_strings: error
    use_rethrow_when_possible: error
    use_setters_to_change_properties: info # Has some false-positive cases. "Info" for now.
    use_string_buffers: warning # Will require some refactoring. "Warning" for now.
    use_to_and_as_if_applicable: info
    void_checks: error

linter:
  rules:
    #
    # Error rules
    #
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - cancel_subscriptions
    # - close_sinks # not reliable enough
    - comment_references
    - control_flow_in_finally
    - diagnostic_describe_all_properties
    - empty_statements
    - hash_and_equals
    - collection_methods_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    # - prefer_relative_imports # will cause a huge refactoring
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - use_key_in_widget_constructors
    - valid_regexps
    #
    # Style rules
    #
    - always_declare_return_types
    - always_put_required_named_parameters_first # Flutter's `key` convention doesn't play well with it
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - combinators_ordering
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - implementation_imports
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - non_constant_identifier_names
    - null_closures
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - sized_box_for_whitespace # available in Dart SDK 2.9.0
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks