name: codegen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dev_dependencies:
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

dependencies:
  flutter:
    sdk: flutter
  rempc:
    path: ../app
