name: app_camera

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  api:
    path: ../api
  core:
    path: ../core
  firebase:
    path: ../firebase
  uikit:
    path: ../uikit
  json_reader:
    path: ../../packages/json_reader
  preference:
    path: ../../packages/preference
  camerawesome: ^1.4.0