name: back_blocker
description: A new flutter plugin project.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ua.bank2.back_blocker
        pluginClass: BackBlockerPlugin
