name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 2.0.0

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.12.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: # use version from outside
  rxdart: # use version from outside
  package_info: # use version from outside
  path_provider: # use version from outside
  permission_handler: # use version from outside
  share_plus: # use version from outside
