name: uikit

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  dotted_border: ^2.1.0
  multi_dropdown: ^2.1.1
  syncfusion_flutter_sliders: ^23.2.5
  modal_bottom_sheet: ^3.0.0-pre

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/2x/
    - assets/3x/