name: core

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dictionary:
    path: ../dictionary
  uikit:
    path: ../uikit
  back_blocker:
    path: ../../packages/back_blocker
  preference:
    path: ../../packages/preference
  json_reader:
    path: ../../packages/json_reader
  device_info_plus: ^9.1.0
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  flutter_chat_ui: ^1.6.9
  app_settings: ^5.1.1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  infinite_scroll_pagination: ^4.0.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  equatable: ^2.0.5
  permission_handler: ^11.0.1
  intl: ^0.18.1
  map_launcher: ^3.0.1
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  modal_bottom_sheet: ^3.0.0-pre
  path_provider: ^2.1.1
  shake: ^2.2.0
  sliding_up_panel: ^2.0.0+1
  flutter_inappwebview: ^5.8.0
  auto_size_text: ^3.0.0
  multi_select_flutter: ^4.1.3