name: api

publish_to: 'none'

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.4
  connectivity_plus: ^5.0.2
  http: ^1.1.0
  core:
    path: ../core
  uikit:
    path: ../uikit
  alice:
    path: ../../packages/alice
  json_reader:
    path: ../../packages/json_reader
  preference:
    path: ../../packages/preference