name: repository

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  api:
    path: ../api
  core:
    path: ../core
  json_reader:
    path: ../../packages/json_reader
  preference:
    path: ../../packages/preference